/**
 * Phase 4D: Gold Evaluation Sentences
 *
 * 70 curated sentences for F1 evaluation of the tree pipeline.
 * Split into 3 subsets:
 *   - organizational (50): copular/definitional + SVO organizational patterns
 *   - coordination  (20): coordinated NNPs requiring split/keep decisions
 *
 * Each sentence has:
 *   - id: unique identifier
 *   - text: input sentence
 *   - subset: 'organizational' | 'coordination'
 *   - expectedEntities: gold entity annotations [{text, type}]
 *   - expectedRoles: gold role annotations [{entity, role}]
 *   - tags: metadata tags
 *
 * NOTE: expectedEntities and expectedRoles are initially generated by the
 * pipeline (via generate-baseline.js) and then expert-reviewed/adjusted.
 * Until expert review, these serve as snapshot baselines.
 */

'use strict';

const sentences = [
  // ==========================================================================
  // Subset: organizational — Copular / Definitional (25)
  // ==========================================================================
  {
    id: 'org-cop-001',
    text: 'CBP is a component of DHS',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'CBP', type: 'cco:Organization' },
      { text: 'DHS', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-002',
    text: 'The FBI is a federal law enforcement agency',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'The FBI', type: 'cco:Organization' },
      { text: 'a federal law enforcement agency', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-003',
    text: 'Border Patrol is the enforcement arm of CBP',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'Border Patrol', type: 'cco:Organization' },
      { text: 'CBP', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-004',
    text: 'FEMA is responsible for disaster relief',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'FEMA', type: 'cco:Organization' },
      { text: 'disaster relief', type: 'bfo:Process' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-005',
    text: 'The Department of Justice is a cabinet-level department',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'The Department of Justice', type: 'cco:Organization' },
      { text: 'a cabinet-level department', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-006',
    text: 'ICE is an agency within DHS',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'ICE', type: 'cco:Organization' },
      { text: 'DHS', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-007',
    text: 'The Secret Service is a federal agency',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'The Secret Service', type: 'cco:Organization' },
      { text: 'a federal agency', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-008',
    text: 'TSA is responsible for transportation security',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'TSA', type: 'cco:Organization' },
      { text: 'transportation security', type: 'bfo:Process' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-009',
    text: 'The Coast Guard is a branch of the armed forces',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'military'],
    expectedEntities: [
      { text: 'The Coast Guard', type: 'cco:Organization' },
      { text: 'the armed forces', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-010',
    text: 'DEA is the primary federal drug enforcement agency',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'DEA', type: 'cco:Organization' },
      { text: 'the primary federal drug enforcement agency', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-011',
    text: 'The CIA is an intelligence agency',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'intelligence'],
    expectedEntities: [
      { text: 'The CIA', type: 'cco:Organization' },
      { text: 'an intelligence agency', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-012',
    text: 'NASA is an independent agency of the federal government',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'NASA', type: 'cco:Organization' },
      { text: 'the federal government', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-013',
    text: 'The attorney general is the head of the Department of Justice',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'The attorney general', type: 'cco:Person' },
      { text: 'the Department of Justice', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-014',
    text: 'A field office is a regional operational unit',
    subset: 'organizational',
    tags: ['copular', 'definitional'],
    expectedEntities: [
      { text: 'A field office', type: 'cco:Organization' },
      { text: 'a regional operational unit', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'org-cop-015',
    text: 'The inspector general is an independent oversight official',
    subset: 'organizational',
    tags: ['copular', 'definitional', 'government'],
    expectedEntities: [
      { text: 'The inspector general', type: 'cco:Person' },
      { text: 'an independent oversight official', type: 'cco:Person' }
    ],
    expectedRoles: []
  },

  // ==========================================================================
  // Subset: organizational — SVO Action Patterns (25)
  // ==========================================================================
  {
    id: 'org-svo-001',
    text: 'The FBI investigated the case',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The FBI', type: 'cco:Organization' },
      { text: 'the case', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'FBI', role: 'Agent' },
      { entity: 'case', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-002',
    text: 'CBP apprehended the suspect at the border',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'CBP', type: 'cco:Organization' },
      { text: 'the suspect', type: 'cco:Person' },
      { text: 'the border', type: 'cco:Facility' }
    ],
    expectedRoles: [
      { entity: 'CBP', role: 'Agent' },
      { entity: 'suspect', role: 'Patient' },
      { entity: 'border', role: 'Location' }
    ]
  },
  {
    id: 'org-svo-003',
    text: 'The committee reviewed the proposal',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The committee', type: 'cco:Organization' },
      { text: 'the proposal', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'committee', role: 'Agent' },
      { entity: 'proposal', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-004',
    text: 'The agent filed a report with the office',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The agent', type: 'cco:Person' },
      { text: 'a report', type: 'cco:InformationContentEntity' },
      { text: 'the office', type: 'cco:Organization' }
    ],
    expectedRoles: [
      { entity: 'agent', role: 'Agent' },
      { entity: 'report', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-005',
    text: 'The director authorized the operation',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The director', type: 'cco:Person' },
      { text: 'the operation', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'director', role: 'Agent' },
      { entity: 'operation', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-006',
    text: 'The officer detained the individual',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The officer', type: 'cco:Person' },
      { text: 'the individual', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'officer', role: 'Agent' },
      { entity: 'individual', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-007',
    text: 'The analyst prepared the intelligence briefing',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The analyst', type: 'cco:Person' },
      { text: 'the intelligence briefing', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'analyst', role: 'Agent' },
      { entity: 'intelligence briefing', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-008',
    text: 'The task force coordinated the response',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The task force', type: 'cco:Organization' },
      { text: 'the response', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'task force', role: 'Agent' },
      { entity: 'response', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-009',
    text: 'The inspector examined the evidence',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The inspector', type: 'cco:Person' },
      { text: 'the evidence', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'inspector', role: 'Agent' },
      { entity: 'evidence', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-010',
    text: 'The secretary issued a statement',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The secretary', type: 'cco:Person' },
      { text: 'a statement', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'secretary', role: 'Agent' },
      { entity: 'statement', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-011',
    text: 'The agency deployed additional personnel',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The agency', type: 'cco:Organization' },
      { text: 'additional personnel', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'agency', role: 'Agent' },
      { entity: 'personnel', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-012',
    text: 'The marshal transported the prisoner to the courthouse',
    subset: 'organizational',
    tags: ['svo', 'government', 'action', 'pp'],
    expectedEntities: [
      { text: 'The marshal', type: 'cco:Person' },
      { text: 'the prisoner', type: 'cco:Person' },
      { text: 'the courthouse', type: 'cco:Facility' }
    ],
    expectedRoles: [
      { entity: 'marshal', role: 'Agent' },
      { entity: 'prisoner', role: 'Patient' },
      { entity: 'courthouse', role: 'Goal' }
    ]
  },
  {
    id: 'org-svo-013',
    text: 'The forensic team analyzed the samples',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The forensic team', type: 'cco:Organization' },
      { text: 'the samples', type: 'bfo:Entity' }
    ],
    expectedRoles: [
      { entity: 'forensic team', role: 'Agent' },
      { entity: 'samples', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-014',
    text: 'The prosecutor presented the evidence to the jury',
    subset: 'organizational',
    tags: ['svo', 'government', 'action', 'pp'],
    expectedEntities: [
      { text: 'The prosecutor', type: 'cco:Person' },
      { text: 'the evidence', type: 'cco:InformationContentEntity' },
      { text: 'the jury', type: 'cco:Organization' }
    ],
    expectedRoles: [
      { entity: 'prosecutor', role: 'Agent' },
      { entity: 'evidence', role: 'Patient' },
      { entity: 'jury', role: 'Recipient' }
    ]
  },
  {
    id: 'org-svo-015',
    text: 'The witness provided testimony',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The witness', type: 'cco:Person' },
      { text: 'testimony', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'witness', role: 'Agent' },
      { entity: 'testimony', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-016',
    text: 'The patrol unit secured the perimeter',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The patrol unit', type: 'cco:Organization' },
      { text: 'the perimeter', type: 'bfo:Entity' }
    ],
    expectedRoles: [
      { entity: 'patrol unit', role: 'Agent' },
      { entity: 'perimeter', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-017',
    text: 'The department implemented new regulations',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The department', type: 'cco:Organization' },
      { text: 'new regulations', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'department', role: 'Agent' },
      { entity: 'regulations', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-018',
    text: 'The auditor discovered discrepancies in the records',
    subset: 'organizational',
    tags: ['svo', 'government', 'action', 'pp'],
    expectedEntities: [
      { text: 'The auditor', type: 'cco:Person' },
      { text: 'discrepancies', type: 'bfo:Entity' },
      { text: 'the records', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'auditor', role: 'Agent' },
      { entity: 'discrepancies', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-019',
    text: 'The judge sentenced the defendant',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The judge', type: 'cco:Person' },
      { text: 'the defendant', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'judge', role: 'Agent' },
      { entity: 'defendant', role: 'Patient' }
    ]
  },
  {
    id: 'org-svo-020',
    text: 'The bureau conducted an investigation',
    subset: 'organizational',
    tags: ['svo', 'government', 'action'],
    expectedEntities: [
      { text: 'The bureau', type: 'cco:Organization' },
      { text: 'an investigation', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'bureau', role: 'Agent' },
      { entity: 'investigation', role: 'Patient' }
    ]
  },
  {
    id: 'org-pass-001',
    text: 'The suspect was apprehended by the officers',
    subset: 'organizational',
    tags: ['passive', 'government', 'action'],
    expectedEntities: [
      { text: 'The suspect', type: 'cco:Person' },
      { text: 'the officers', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'officers', role: 'Agent' },
      { entity: 'suspect', role: 'Patient' }
    ]
  },
  {
    id: 'org-pass-002',
    text: 'The report was submitted to the director',
    subset: 'organizational',
    tags: ['passive', 'government', 'action'],
    expectedEntities: [
      { text: 'The report', type: 'cco:InformationContentEntity' },
      { text: 'the director', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'report', role: 'Patient' },
      { entity: 'director', role: 'Recipient' }
    ]
  },
  {
    id: 'org-pass-003',
    text: 'The policy was approved by the committee',
    subset: 'organizational',
    tags: ['passive', 'government', 'action'],
    expectedEntities: [
      { text: 'The policy', type: 'cco:InformationContentEntity' },
      { text: 'the committee', type: 'cco:Organization' }
    ],
    expectedRoles: [
      { entity: 'committee', role: 'Agent' },
      { entity: 'policy', role: 'Patient' }
    ]
  },
  {
    id: 'org-ditr-001',
    text: 'The commander gave the team new orders',
    subset: 'organizational',
    tags: ['ditransitive', 'government', 'action'],
    expectedEntities: [
      { text: 'The commander', type: 'cco:Person' },
      { text: 'the team', type: 'cco:Organization' },
      { text: 'new orders', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'commander', role: 'Agent' },
      { entity: 'team', role: 'Recipient' },
      { entity: 'orders', role: 'Patient' }
    ]
  },
  {
    id: 'org-ditr-002',
    text: 'The supervisor assigned the officer a new case',
    subset: 'organizational',
    tags: ['ditransitive', 'government', 'action'],
    expectedEntities: [
      { text: 'The supervisor', type: 'cco:Person' },
      { text: 'the officer', type: 'cco:Person' },
      { text: 'a new case', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'supervisor', role: 'Agent' },
      { entity: 'officer', role: 'Recipient' },
      { entity: 'case', role: 'Patient' }
    ]
  },

  // ==========================================================================
  // Subset: coordination — NNP Split/Keep Decisions (20)
  // ==========================================================================
  {
    id: 'coord-split-001',
    text: 'The FBI and CIA coordinated the operation',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'The FBI', type: 'cco:Organization' },
      { text: 'CIA', type: 'cco:Organization' },
      { text: 'the operation', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'FBI', role: 'Agent' },
      { entity: 'CIA', role: 'Agent' },
      { entity: 'operation', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-002',
    text: 'CBP and ICE are components of DHS',
    subset: 'coordination',
    tags: ['coordination', 'split', 'copular', 'government'],
    expectedEntities: [
      { text: 'CBP', type: 'cco:Organization' },
      { text: 'ICE', type: 'cco:Organization' },
      { text: 'DHS', type: 'cco:Organization' }
    ],
    expectedRoles: []
  },
  {
    id: 'coord-split-003',
    text: 'The agent and the analyst reviewed the evidence',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'The agent', type: 'cco:Person' },
      { text: 'the analyst', type: 'cco:Person' },
      { text: 'the evidence', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'agent', role: 'Agent' },
      { entity: 'analyst', role: 'Agent' },
      { entity: 'evidence', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-004',
    text: 'The director and the deputy authorized the mission',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'The director', type: 'cco:Person' },
      { text: 'the deputy', type: 'cco:Person' },
      { text: 'the mission', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'director', role: 'Agent' },
      { entity: 'deputy', role: 'Agent' },
      { entity: 'mission', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-005',
    text: 'FEMA and the Red Cross provided disaster relief',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'FEMA', type: 'cco:Organization' },
      { text: 'the Red Cross', type: 'cco:Organization' },
      { text: 'disaster relief', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'FEMA', role: 'Agent' },
      { entity: 'Red Cross', role: 'Agent' },
      { entity: 'disaster relief', role: 'Patient' }
    ]
  },
  {
    id: 'coord-keep-001',
    text: 'The Department of Homeland Security issued the directive',
    subset: 'coordination',
    tags: ['coordination', 'keep', 'government'],
    expectedEntities: [
      { text: 'The Department of Homeland Security', type: 'cco:Organization' },
      { text: 'the directive', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'Department of Homeland Security', role: 'Agent' },
      { entity: 'directive', role: 'Patient' }
    ]
  },
  {
    id: 'coord-keep-002',
    text: 'Customs and Border Protection enforces trade laws',
    subset: 'coordination',
    tags: ['coordination', 'keep', 'government'],
    expectedEntities: [
      { text: 'Customs and Border Protection', type: 'cco:Organization' },
      { text: 'trade laws', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'Customs and Border Protection', role: 'Agent' },
      { entity: 'trade laws', role: 'Patient' }
    ]
  },
  {
    id: 'coord-keep-003',
    text: 'The Bureau of Alcohol Tobacco and Firearms investigated the case',
    subset: 'coordination',
    tags: ['coordination', 'keep', 'government'],
    expectedEntities: [
      { text: 'The Bureau of Alcohol Tobacco and Firearms', type: 'cco:Organization' },
      { text: 'the case', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'Bureau of Alcohol Tobacco and Firearms', role: 'Agent' },
      { entity: 'case', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-006',
    text: 'Agents and officers conducted the raid',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'Agents', type: 'cco:Person' },
      { text: 'officers', type: 'cco:Person' },
      { text: 'the raid', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'Agents', role: 'Agent' },
      { entity: 'officers', role: 'Agent' },
      { entity: 'raid', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-007',
    text: 'The suspect and the accomplice were arrested',
    subset: 'coordination',
    tags: ['coordination', 'split', 'passive'],
    expectedEntities: [
      { text: 'The suspect', type: 'cco:Person' },
      { text: 'the accomplice', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'suspect', role: 'Patient' },
      { entity: 'accomplice', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-008',
    text: 'The inspector reviewed the documents and the photographs',
    subset: 'coordination',
    tags: ['coordination', 'split', 'object'],
    expectedEntities: [
      { text: 'The inspector', type: 'cco:Person' },
      { text: 'the documents', type: 'cco:InformationContentEntity' },
      { text: 'the photographs', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'inspector', role: 'Agent' },
      { entity: 'documents', role: 'Patient' },
      { entity: 'photographs', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-009',
    text: 'TSA and CBP implemented new screening procedures',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'TSA', type: 'cco:Organization' },
      { text: 'CBP', type: 'cco:Organization' },
      { text: 'new screening procedures', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'TSA', role: 'Agent' },
      { entity: 'CBP', role: 'Agent' },
      { entity: 'screening procedures', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-010',
    text: 'The prosecutor and the defense attorney addressed the court',
    subset: 'coordination',
    tags: ['coordination', 'split', 'legal'],
    expectedEntities: [
      { text: 'The prosecutor', type: 'cco:Person' },
      { text: 'the defense attorney', type: 'cco:Person' },
      { text: 'the court', type: 'cco:Organization' }
    ],
    expectedRoles: [
      { entity: 'prosecutor', role: 'Agent' },
      { entity: 'defense attorney', role: 'Agent' },
      { entity: 'court', role: 'Recipient' }
    ]
  },
  {
    id: 'coord-keep-004',
    text: 'Fish and Wildlife Service manages protected areas',
    subset: 'coordination',
    tags: ['coordination', 'keep', 'government'],
    expectedEntities: [
      { text: 'Fish and Wildlife Service', type: 'cco:Organization' },
      { text: 'protected areas', type: 'cco:Facility' }
    ],
    expectedRoles: [
      { entity: 'Fish and Wildlife Service', role: 'Agent' },
      { entity: 'protected areas', role: 'Patient' }
    ]
  },
  {
    id: 'coord-keep-005',
    text: 'Immigration and Customs Enforcement deported the individual',
    subset: 'coordination',
    tags: ['coordination', 'keep', 'government'],
    expectedEntities: [
      { text: 'Immigration and Customs Enforcement', type: 'cco:Organization' },
      { text: 'the individual', type: 'cco:Person' }
    ],
    expectedRoles: [
      { entity: 'Immigration and Customs Enforcement', role: 'Agent' },
      { entity: 'individual', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-011',
    text: 'The agents searched the building and the vehicle',
    subset: 'coordination',
    tags: ['coordination', 'split', 'object'],
    expectedEntities: [
      { text: 'The agents', type: 'cco:Person' },
      { text: 'the building', type: 'cco:Facility' },
      { text: 'the vehicle', type: 'cco:Artifact' }
    ],
    expectedRoles: [
      { entity: 'agents', role: 'Agent' },
      { entity: 'building', role: 'Patient' },
      { entity: 'vehicle', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-012',
    text: 'DEA and FBI launched a joint investigation',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'DEA', type: 'cco:Organization' },
      { text: 'FBI', type: 'cco:Organization' },
      { text: 'a joint investigation', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'DEA', role: 'Agent' },
      { entity: 'FBI', role: 'Agent' },
      { entity: 'investigation', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-013',
    text: 'The captain and the lieutenant briefed the team',
    subset: 'coordination',
    tags: ['coordination', 'split', 'military'],
    expectedEntities: [
      { text: 'The captain', type: 'cco:Person' },
      { text: 'the lieutenant', type: 'cco:Person' },
      { text: 'the team', type: 'cco:Organization' }
    ],
    expectedRoles: [
      { entity: 'captain', role: 'Agent' },
      { entity: 'lieutenant', role: 'Agent' },
      { entity: 'team', role: 'Recipient' }
    ]
  },
  {
    id: 'coord-split-014',
    text: 'The senator and the representative sponsored the bill',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'The senator', type: 'cco:Person' },
      { text: 'the representative', type: 'cco:Person' },
      { text: 'the bill', type: 'cco:InformationContentEntity' }
    ],
    expectedRoles: [
      { entity: 'senator', role: 'Agent' },
      { entity: 'representative', role: 'Agent' },
      { entity: 'bill', role: 'Patient' }
    ]
  },
  {
    id: 'coord-split-015',
    text: 'State and local authorities assisted in the search',
    subset: 'coordination',
    tags: ['coordination', 'split', 'government'],
    expectedEntities: [
      { text: 'State', type: 'cco:Organization' },
      { text: 'local authorities', type: 'cco:Organization' },
      { text: 'the search', type: 'bfo:Process' }
    ],
    expectedRoles: [
      { entity: 'State', role: 'Agent' },
      { entity: 'local authorities', role: 'Agent' }
    ]
  }
];

module.exports = sentences;
